// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package openapi

// アイテム
type Item struct {
	// アイテム説明
	Description *string `json:"description,omitempty"`
	Id          string  `json:"id"`

	// アイテム名
	Name string `json:"name"`

	// 価格
	Price int `json:"price"`
}

// PostItemsJSONBody defines parameters for PostItems.
type PostItemsJSONBody = Item

// PostItemsJSONRequestBody defines body for PostItems for application/json ContentType.
type PostItemsJSONRequestBody = PostItemsJSONBody
